[package]
name = "kyusa"
version = "0.4.0"
authors = [ "Tyler Hill <tyhi@tyhi.rs" ]
edition = "2018"
repository = "https://github.com/tyhi/kyusa"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.2.2"
actix-multipart = "0.2.0"
actix-rt = "1.1.1"
actix-web = "2.0.0"
anyhow = "1.0.31"
dotenv = "0.15.0"
futures = "0.3.5"
mimalloc = { version = "0.1.19", default-features = false }
serde = "1.0.114"
serde_json = "1.0.56"
tokio = { version = "0.2.21", features = [ "fs", "rt-core", "blocking" ] }
sqlx = { git = "https://github.com/launchbadge/sqlx", default-features = false, features = [ "runtime-tokio", "macros", "postgres" ] }
short_url = { git = "https://github.com/tyhi/short_url-rs" }
blake3 = "0.3.4"
once_cell = "1.4.0"
fastrand = "1.3.2"

[build-dependencies]
built = { version = "0.4.2", features = [ "git2" ] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

