[package]
name = "kyusa"
version = "0.2.0"
authors = ["Tyler Hill <tyhi@tyhi.rs"]
edition = "2018"
repository = "https://github.com/tyhi/kyusa"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.8"
awmp = "0.4.1"
sled = "0.29.2"
bincode = "1.2.0"
serde = "1.0.102"
nanoid = "0.2.0"
actix-files = "0.1.6"
serde_json = "1.0.41"
chrono = {version = "0.4.9", features = ["serde"]}
http = "0.1.19"
addr = "0.2.0"

[dependencies.isahc]
version = "0.8.1"
features = ["json"]

[build-dependencies]
built = "0.3.2"
