[package]
name = "keou"
version = "0.1.0"
authors = ["tyhi"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.7"
awmp = "0.3.0"
sled = "0.26.3"
bincode = "1.1.4"
serde = "1.0.99"
nanoid = "0.2.0"
actix-files = "0.1.4"
serde_json = "1.0.40"
chrono = {version = "0.4.7", features = ["serde"]}
log = "0.4.8"
env_logger = "0.6.2"
http = "0.1.18"
addr = "0.2.0"

[dependencies.isahc]
version = "0.7.1"
features = ["json"]

[build-dependencies]
built = "0.3.2"