[package]
name = "kyusa"
version = "0.3.0"
authors = ["Tyler Hill <tyhi@tyhi.rs"]
edition = "2018"
repository = "https://github.com/tyhi/kyusa"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfp-rs = "0.2.0"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-multipart = "0.2.0"
serde = "1.0.104"
nanoid = "0.2.0"
actix-files = "0.2.1"
serde_json = "1.0.44"
chrono = {version = "0.4.10", features = ["serde"]}
futures = "0.3.1"
sqlx = { version = "0.2", default-features = false, features = [ "runtime-tokio", "macros", "uuid", "postgres", "chrono" ] }
uuid = {version = "0.8.1", features = ["serde"]}
dotenv = "0.15.0"

[build-dependencies]
built = "0.3.2"
