[package]
name = "kyusa"
version = "0.4.0"
authors = [ "Tyler Hill <tyhi@tyhi.rs" ]
edition = "2018"
repository = "https://github.com/tyhi/kyusa"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.3.0-alpha.1"
actix-multipart = "0.3.0-alpha.1"
actix-rt = "1.1.1"
actix-web = "3.0.0-alpha.3"
anyhow = "1.0.31"
dotenv = "0.15.0"
futures = "0.3.5"
mimalloc = { version = "0.1.19", default-features = false }
serde = "1.0.114"
serde_json = "1.0.56"
tokio = { version = "0.2.21", features = [ "fs", "macros" ] }
sqlx = { git = "https://github.com/launchbadge/sqlx", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "offline" ] }
short_url = { git = "https://github.com/tyhi/short_url-rs" }
blake3 = "0.3.5"
once_cell = "1.4.0"
fastrand = "1.3.3"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

