[package]
name = "kyusa"
version = "0.4.0"
authors = [ "Tyler Hill <tyhi@tyhi.rs" ]
edition = "2018"
repository = "https://github.com/tyhi/kyusa"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.2.2"
actix-multipart = "0.2.0"
actix-rt = "1.1.1"
actix-web = "2.0.0"
anyhow = "1.0.31"
bincode = "1.2.1"
chrono = { version = "0.4.11", features = [ "serde" ] }
dotenv = "0.15.0"
futures = "0.3.5"
mimalloc = { version = "0.1.19", default-features = false }
nanoid = "0.3.0"
reqwest = "0.10.4"
serde = "1.0.110"
serde_json = "1.0.53"
sled = { version = "0.31.0", features = ["compression"] }
tokio = { version = "0.2.21", features = [ "fs", "rt-core", "blocking" ] }

[build-dependencies]
built = { version = "0.4.2", features = [ "git2" ] }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

