name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        profile: default
        toochain: nightly
    - name: Build
      run: cargo build --verbose
