name: CI

on: [push, pull_request]

jobs:
  rust:
    name: Rust

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: ["nightly"]

    runs-on: ${{ matrix.os }}

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          default: true

      - name: Build (secure)
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test (secure)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features

      - name: Build (no secure)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features

      - name: Test (no secure)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features

  lint:
    name: Rustfmt / Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: +nightly --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: +nightly clippy
